import pygame

SCREEN_RECT = pygame.Rect(0, 0, 480, 700)
GAME_FRAME = 60
HERO_FIRE_EVENT = pygame.USEREVENT + 1
HERO_FIRE_INTERVAL = 200
ENEMY_SPAWN_EVENT = pygame.USEREVENT + 2
ENEMY_SPAWN_TIME = 1000

ENEMY_SPEED_MIN = 1
ENEMY_SPEED_MAX = 5
